---

- name: exercise 2.1
  hosts: cisco
 
  tasks:
    - name: ios_facts
      ios_facts:
        #gather_subset: all
        provider:
          username: pyclass
          password: 88newclass
          host: "{{ ansible_host }}"
      register: result

    - name: get_serial
      debug:
        msg: "The serial number is {{ ansible_net_serialnum }}"
