---

- name: exercise 3
  hosts: nxos 
  vars:
    vlan:
       vlan_id: 301
       admin_state: up
       name: blue
 
  tasks:
    - name: add vlans
      nxos_vlan:
        provider:
          "{{ nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        admin_state: "{{ item.admin_state }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans_total }}" 
      tags:
        - 3z
      notify: save_config

  handlers:
    - name: save_config
      nxos_config:
        lines:
          - copy run start 
        provider:
          "{{ nxapi }}"
      tags: 4z
